### ISSUE TITLE
Remove children?

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#105]
We have `context.content.children` marked as deprecated in our schema, should we also remove it?

@kptdobe the project-helix.io code uses it at the moment and would need to get refactored.

**Comment by kptdobe** [comment]
`children` is also currently in use here: https://github.com/adobe/Adobe-Developer-Site/tree/master/src

**Comment by filmaj** [comment]
I was struggling with this yesterday playing around with the dev site.

[The docs say to use `document.children[]` instead](https://github.com/adobe/helix-pipeline/blob/master/docs/content.schema.md#children), but that gives the entire document's children, not the subsection being rendered. Not sure if that's by design or a bug. I don't think the dev site could do a straight-up swap from using `content.children` to `content.document.children` [in its template](https://github.com/adobe/Adobe-Developer-Site/blob/master/src/html.htl#L68).

**Comment by kptdobe** [comment]
I created https://github.com/adobe/Adobe-Developer-Site/issues/45 to track the work.
