### ISSUE TITLE
Conditional Polyfills

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#121]
While working with @rofe on #120 I noticed the PR he made to https://github.com/adobe/Adobe-Developer-Site/issues/34 which is effectively disabling a polyfill created in the project code to circumvent a lack of production functionality (#25)

It would be cool to have self-disabling polyfill functionality that can be used in a project's `pre.js` like this:

```javascript
function pre(context, action) {
  action.polyfill('hypermedia-pipeline#122', () => {
    // this will only be run as long as hypermedia-pipeline#122 is not fixed
    context.fixme = 'true';
  });
}
```

This way, projects that need certain product functionality can go through following process:

1. create a new feature request in hypermedia-pipeline
2. implement a quick and dirty fix in the project
3. `action.polyfill` flag it with the issue number received in (1)
4. deploy
5. wait for the product to deliver a generalized fix
6. update dependencies
7. re-deploy
8. the code that was guarded in (3) will never be run again

We would need to maintain a list of fixed issues, but this can be generated easily as part of the build process.

**Comment by rofe** [comment]
I like the general idea, this would help keep custom fixes tidy and make it easy to upgrade to the latest Helix code. But I see a challenge: how can we know if an issue was closed fixed versus closed invalid/rejected/wontfix? we might also need to search for commits mentioning the issue and verify that they actually made it into the release which is currently deployed...

**Comment by tripodsan** [comment]
I would rely on normal github fork-develop-pr-merge workflow:

1. create a new feature request in hypermedia-pipeline
2. fork hypermedia pipeline
3. implement a (quick and dirty) fix in the project
4. use custom pipeline and deploy
5. create PR with your fix.
6. wait for the product to merge in your fix or deliver a generalized fix
7. use original pipeline again.
8. re-deploy

**Comment by tripodsan** [comment]
However, I would not call this a polyfill, but a feature-flag.
well, the custom code is a polyfill in some way, but the guard around is the feature-flag.

**Comment by kptdobe** [comment]
Just to be clear - in a real life scenario (we have 10k customers live):

* #120 is a breaking change: we change the payload contract. Thus in reality, it would have to be handled differently.
* "use custom pipeline and deploy" should not be possible since we managed the stuff.

Thus in that scenario, the process should more be something like:

1. create a new feature request in "helix" (as a customer, you do not necessarily know which part we are talking about)
2. if feature request is not approved, you keep your workaround forever
3. if feature request is approved, you get a feature-flag id and the new API description... can code you stuff accordingly to disable the workaround when feature is available
4. all customers get the change in a non breaking mode

I would rather start thinking in that mode than start assuming our customers can hack helix...

**Comment by trieloff** [comment]
Closing for now.
