### ISSUE TITLE
Tap Chaos

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#133]
Expand the pipeline with an optional step that can be added at any time (or even as a tap, for every step) that adds chaos to the processing (disabled in production, of course). This step can randomly:
- Exit
- Change values in the pipeline
- Add values to the pipeline
- Drop values from the pipeline
- Go sloooooow

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kptdobe** [comment]
-1
This goes against the common sense and good development practices... feels like / shows we do not have control on our source code anymore...
I would rather invest into good testing practices, strong code, well defined APIs: 
- tests all exist cases included unexpected ones
- the schema definition you did is great, if change / add / drop values is a potential issue, either we need to make the schema stronger or clearly define the extension points or spaces / rules for values mutations
- slowness and even timeout should / could be tested per method or in integration tests

This probably also means:
- set strict npm dependencies so that we do track (and test) dependency updates
- build less features
