### ISSUE TITLE
Should the Pipeline Merge?

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#223]
@trieloff I've run into some problems last friday when trying to add the frontmatter parse step into the actual pipline and this morning I was finally able to figure out the problem…
The pipeline property merger is adding all the mdast nodes to the mdast which I previously replaced with frontmatter nodes.
How can we disable that behaviour?

Btw, I think we might want to think about how we approach property merging in general again…
To me it seems that merging arrays is generally not what we want; AFAICS using _.merge also means we cannot delete data in pipeline steps, as the merging step will just reverse that deletion. Merging complex ASTs like mdast and htast could especially lead to weirdness deep in the tree…

I think the last two points might be espeically confusing to third party devs trying to write their own pipeline steps…

_Originally posted by @koraa in https://github.com/adobe/helix-pipeline/pull/206#issuecomment-476153897_

**Comment by trieloff** [comment]
The inability to remove stuff from the payload is definitely surprising and a downside. On the other hand, the ability to just return the stuff you'd like to add is a definitive benefit.

Maybe we can find a merge semantic that is a bit more intuitive, e.g. one that merges objects as before, but replaces arrays.

**Comment by tripodsan** [comment]
> On the other hand, the ability to just return the stuff you'd like to add is a definitive benefit.

I think it's overrated :-) it think it's more transparent to either modify the `context` directly (people are used to write _middleware_, that operate on the _request_ / _response_ (eg. `res.set('content-type', ...))`. or the return (and replace) the existing `context`

we could be smart, and only merge in new properties and throw an error when trying to overwrite old ones. but I think less magic is always better.

#### Suggest:

- the return value of a pipeline function will replace the existing `context`, if the returned value (or the resolved value of a returned promise) is an object.
- in all other cases, the current `context` is retained.
- the pipeline function is allowed to modify the `context` object directly.

**Comment by trieloff** [comment]
I've been chatting with @koraa yesterday and came up with another heuristic:

- default is to overwrite
- unless overwriting would cause the loss of a root property of the payload

This would allow existing steps to work unchanged, as they return sparse payloads (so the merge would take hold), but you can write steps that return rich payloads which would replace the existing payload.

**Comment by tripodsan** [comment]
> unless overwriting would cause the loss of a root property of the payload

and then?

**Comment by trieloff** [comment]
and then, we merge (I've edited it)

**Comment by koraa** [comment]
I tend to concur with @tripodsan; I see no real benefit of merging over just setting the property; especially since that is pretty much just what we want to do in every step…

Just assigning values should also be much more transparent to people trying to write their own pipeline steps: they are used to seeing `(foo) => foo.bar = 42`, the merge semantics are something that every dev using helix would have to learn…

It would be a different matter to me if we actually went the functional route and discarded the entire input value…

**Comment by koraa** [comment]
@trieloff I think overwriting if all root properties are present and merging otherwise would be associated with pretty much the same problems in most cases as merging is now.

I think the currently intended semantic is that merging is limited to `root` objects (*, content.*); such a scheme could be easily implemented:

```
each(returned, ([key, value]) => {
  if (key !== 'content') {
    context[key] = value;
  }
}
each(returned.content || {}, ([key, value]) => {
  context.content[key] = value;
});
```

Although TBH I still don't see an advantage over allowing assigments in pipeline steps…
