### ISSUE TITLE
openwhisk emulator should pass request body to pipeline

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pipeline#235]
If there is a `body.content` in the `actionParams`, add it to the `payload` (like openwhisk would). Depends on https://github.com/adobe/helix-simulator/issues/179.

**Comment by tripodsan** [comment]
Why does openwhisk do this?

**Comment by rofe** [comment]
I don't know :)

All I know is that the html pipe [skips the fetch step](https://github.com/adobe/helix-pipeline/blob/2b8feb8842a15381e1044225518f946c0f0a1444/src/defaults/html.pipe.js#L49) if there is a `content.body` in the payload.

**Comment by tripodsan** [comment]
In general, we have to decide how (and if) we want to handle `POST` requests. either `application/json` bodies, `application/x-www-form-urlencoded` and `multipart/form-data`.

### Fastly
currently, and `POST` requests to fastly are not allowed. the internal action delegation makes heavy use of request parameters, which are manifested in the actions `params` eg:

```
  "params": {
    "__ow_path": "",
    "extension": "",
    "owner": "tripodsan",
    "params": "",
    "path": "/index.md",
    "ref": "master",
    "repo": "hlxtest",
    "rootPath": "",
    "selector": "",
    "strain": "default"
  },
```

So even if we allow `POST` requests, we have to ensure that they don't override those params. so any handling of form-param, or JSON bodies **MUST NOT** override any action param.

### Openwhisk

Currently, we deploy the actions as normal [web actions](https://github.com/apache/incubator-openwhisk/blob/master/docs/webactions.md#web-actions). one _cool_ feature of them is that:

> The __ow_body property is present either when handling "raw" HTTP requests, or when the HTTP request entity is not a JSON object or form data. Web actions otherwise receive query and body parameters as first class properties in the action arguments with body parameters taking precedence over query parameters, which in turn take precedence over action and package parameters.

As mentioned above, this behaviour is not desired, as it conflicts with the way we invoke the actions via fastly.

as a consequence, we **SHOULD** deploy the script as [raw actions](https://github.com/apache/incubator-openwhisk/blob/master/docs/webactions.md#raw-http-handling) with `--web=raw`. this would imply that that pipeline needs to handle the `__ow_query` parsing.

### Pipeline

Given the pre-conditions above, using `raw` web actions would imply to handle the `__ow_query` in the pipeline (openwhisk.js) and decode them into the `action.params`.

- for a `POST` request with content-type `application/x-www-form-urlencoded`, we **SHOULD** decode them into the `context.request.params` property, since they specify client input.

- for a `POST` request with content-type  `multipart/form-data`, the pipeline **COULD** handle the form data and populate `context.request.params`, or maybe a `context.request.formdata` to provide access to the binaries in some form.

- for a `POST` request with content-type `application/json`, the pipeline **SHOULD** decode the json body and populate `content.request.body`

- for a `POST` request with any other content-type, the pipeline **SHOULD** keep the raw data in `content.request.body` as `Buffer`. this way, application code can easily check with `Buffer.isBuffer()` for raw data.

### Simulator

The helix simulator not only emulates fastly, but also the openwhisk gateway. so any changes to the above, need to be reflected in the simulator:

- use `__ow_query` instead of populating actions params
- create `__ow_body` with base64 encoded request.body for `POST` requests

## Live Preview

For the live preview feature, it should be possible to provide content that overrides the `context.content.body`, in order that the `fetch` pipeline step doesn't load the markdown, but uses the one provided. 

This can be handled by directly invoking the action instead of going through fastly. in this case, it is possible to override the action params via a json `POST`. the difficulty will be to _find_ the correct action :-)

bear in mind that this feature would break, if the actions will be deployed as `raw` actions in the future to handle user input via `POST` requests.

## Conclusion

I think that we currently don't need to change anything in the pipeline, as it should not handle any `POST` bodies directly:

- either the pipeline is invoked via the openwhisk action directly, in this case openwhisk will decode the json body and set the `content` params,
- or the pipeline is invoked via the simulator, which should do the same (https://github.com/adobe/helix-simulator/issues/179)

**Comment by rofe** [comment]
Makes total sense, thanks @tripodsan. For now, I'll close this issue and corresponding PR and focus just on handling POSTs in simulator more openwhisk-like in https://github.com/adobe/helix-simulator/issues/179 .
