### ISSUE TITLE
Investigate reducing VCL and moving some of the code into the action

### ISSUE THREAD

**Issue by koraa** [adobe/helix-pipeline#365]

**Comment by tripodsan** [comment]
I like the idea of exploring this...however, since most of the VCL is dealing with resolving different actions and requests for static, I think this belongs in it's own action and not into the pipeline. all the pipeline can do is to try to load different markdown resources....

also see the complexity of https://github.com/adobe/helix-publish/issues/96

**Comment by trieloff** [comment]
I have been thinking about this all day and can report that I'm in the process of gradually changing my opinion from "no way" (last time I discussed this with @tripodsan) to "it might be worth trying (last time I discussed it with @koraa) to "I think I know how it should be done and why" (right now).

- as @tripodsan said, it should not happen in the pipeline, but in a separate action (e.g. `helix-superfetch`) because we don't want to enforce use of the pipeline, but enable people to deploy actions that just follow the pipeline's API but are implemented independently
- as a separate action, we should maintain it and bind it similar to how we handle `helix-static`, i.e. have one action that is deployed centrally, but mounted into each individual namespace, so that rate limits and access can remain per tenant
- in order to optimize performance, it should make following requests^H `ow.action.invoke`s in parallel:
1. to `helix-static`, but using the `content` repo
2. to the pipeline action
3. (optionally) to the Pipeline action using one or multiple `directoryIndex` fallbacks (one invocation for each directory index)
4. to `helix-static`, but using the `static` repo
5. to `helix-content`, using `404.html` as the resource
6. to `helix-static`, but using the `404.html` as the resource
- the action should deliver the response of the first invocation that does not return an error (but still attempt all in parallel to minimize wait time)
- the action should adjust the cache headers, so that 404 responses are cached for the correct time span
- the action should also inject a surrogate key indicating the potential sources that didn't not get picked, this way we can enforce re-fetching when for instance the content repository has changed, but resources were delivered by the static fallback instead.

**Comment by trieloff** [comment]
After looking at https://github.com/adobe/helix-publish/pull/103 in more detail, I think the approach that is using a `dispatch` or `superfetch` action could even have performance benefits in the uncached scenario because it can run things in parallel that have to run sequentially in VCL.

**Comment by trieloff** [comment]
Another though: given that we have some ESI features we wish Fastly would support, we could just include `nodesi` in the `dispatch` action and process ESI includes in OpenWhisk.

**Comment by tripodsan** [comment]
> Another though: given that we have some ESI features we wish Fastly would support, we could just include `nodesi` in the `dispatch` action and process ESI includes in OpenWhisk.

I spoke recently with @davidnuescheler regarding the problems with ESI, caching, complex VLC. 
Given that the helix vcl is fragile/complicated and most likely not be able to integrate with a customer that already has a Fastly, or has a different Edge alltogether; I suggest to explore the possiblity to use the _helix service_ as an origin for the final service. This would allow for better caching, no ESI includes on the final stage (and support gzip compression). 

just a thought....

**Comment by tripodsan** [comment]
> After looking at [adobe/helix-publish#103](https://github.com/adobe/helix-publish/pull/103) in more detail, I think the approach that is using a `dispatch` or `superfetch` action could even have performance benefits in the uncached scenario because it can run things in parallel that have to run sequentially in VCL.

I thought of this again, and I think there are basically 2 places/options reduce VCL complexity:

### 1. Create a dispatcher action

the most obvious choice could be to create a new `helix-dispatcher` runtime action that acts like a mini edge, similar what we do on the edge with the VCL. e.g. requesting the content, actions, static, etc until a proper response can be found.

this has the advantage, that the complex VCL logic can be expressed in javascript, and we can reduce the complexity of the VCL on the edge to a minimum that gives us a better chance to configure customers services and/or using different edges.

this has the disadvantage, that the backend responses are not cached, unless we go again through fastly, which might have a larger latency.

### 2. Move some complexity to the rendering actions

as started in https://github.com/adobe/helix-cli/pull/983, I think consolidating the github requests that potentially go to the same repository might be benefitial. for that I would do the following:

1. create a module called `loader` or `dispatch` or `superfetch`
2. during `hlx package` all pipeline actions and the `loader` are munged together in 1 runtime action
3. the `loader` is the entry point of the openwhisk action

the `loader` would work as follow:

1. fastly would invoke the action with the original request url, content repository coordinates, root path, etc. This would be the first request (0th restart)
2. the loader would try to fetch the raw resource from the content repository (eg `/about.html`). if found, it would return it. (we might need to use the resource-too-large-redirect-trick...)
3. If the raw resource is not found, the loader would parse the url, figure out `selector` and `extension` and determined the pipeline action name.
4. if the respective pipeline action not available, it returns a 404
5. if found, it runs the pipeline, which will fetch the `.md` etc...

this would be the very minimal approach. it offers some room for features and optimizations:
- for directory requests, the loader could try to load alternatives (eg: `['/index.html', '/README.html']`). probably best by enumerating the directory first.
- the loader could already load the `.md` and then just pass it to the pipeline (which still can do the 404 handling if needed)

What I would **absolutely not** do in the rendering actions, is to access other repositories that the content repository. e.g. no static handling.

---

I think that those 2 approaches are not exclusive. Additional features, like ESI processing, fetching the static resources could still be moved to a separate `helix-dispatch` action.

**Comment by kptdobe** [comment]
Done.
