### ISSUE TITLE
support adding prefetch links to mdast

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-pipeline#519]
Goal is to create a prefetch script that will send a request to helix-run-query, and obtain urls to prefetch. 

Request will need (Google Credentials, ServiceID, FastlyToken, QueryParams)

Response will contain most likely next resources, potential headers set in Query scripts like 'Cache-Control'. 

The script will then; add children nodes to head node; that are links for prefetching.
OR we can set Link HTTP header <

Script will be fault tolerable; and simply continue down the pipeline upon failure. 

A timeout parameter is essential here; as we do not want to hangup on bad connection with BigQuery. Either we timeout; or we delay results until just before HTML generation! 

Related Issues: 
https://github.com/adobe/project-helix/issues/428
https://github.com/adobe/helix-logging/issues/134

**Comment by trieloff** [comment]
I'd suggest a couple of changes:

- we don't want to add the links to the MDAST (parsed markdown), but rather to the `Link` header of the response
- we could also add it as `link` tags to the `head` element of the DOM (which is later parsed and turned into headers anyway, so the first approach is preferred)

The other thing I'd change is how we deal with credentials and which new credentials we have to expose to the pipeline
- Google Credentials: not needed, as you can call `helix-run-query` without them
- Fastly Credentials: I'd like to avoid having to pass them, too: the fewer places we have that store credentials, the better, so if we can find a way to eliminate them, let's do it. Additionally, I'd say that the response of the query does not contain any private information (the list of resources that we'd like to push for a given URL can be observed by anyone equipped with `curl`), so I think we can keep the query results public.

`helix-run-query` doesn't have a way of making query results public, so I've opened https://github.com/adobe/helix-run-query/issues/53

We still might need to pass the Service Config ID unless we can find a good way to construct a reverse lookup of hostname to service config.

**Comment by tripodsan** [comment]
I don't like that we need to delay rendering to fetch the prefetch resources. can't this be done clientside? (or eventually via http/2 server push?)

**Comment by trieloff** [comment]
No, it can't be done client side and it can't be done via HTTP/2 server push. The very point of this exercise is to have the `Link` header at the end of the rendering pipeline populated, so that Fastly can HTTP/2 server-push everything that's in that header.

Having to wait for something that should make things faster is indeed unfortunate. I could imagine an implementation where we have one step in the very beginning of the pipeline, right before `fetch` that will retrieve the list of related resources, but won't `await` the result, but instead stash a `Promise` in the context.

The bulk of the normal processing pipeline proceeds then, including the relatively slow `fetch` step, so that by the time the response can be prepared and the headers injected, the `Promise` created earlier is most likely resolved. If not, we `await` with a short 50 ms timeout and proceed without if we can't get a response.

That means the worst case performance impact of this feature is 50 ms, and we can tone it down if we want to.

**Comment by MarquiseRosier** [comment]
@trieloff Ok; thank you for this critical insight! I agree; 

I really agree with you on making the results public.

Can you explain how helix-logging authenticates initially so that it can create service accounts?

**Comment by MarquiseRosier** [comment]
@trieloff @tripodsan I was thinking of something similar to solve the problem of waiting for the prefetch code; some way of not blocking the rest of the pipeline;  and just poll the for the result

**Comment by tripodsan** [comment]
closing won't fix.
