### ISSUE TITLE
get-metadata is not map-enumeration stable

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#669]
**Description**
the `meta` properties on the mdast nodes are computed based on the entries of an object:

```js
    types.push(...Object.entries(typecounter) // get pairs of type, count
      .sort((left, right) => left[1] < right[1]) // sort descending by count
      .slice(0, 3) // take the top three
      .map(([name]) => name) // keep only the type
      .reduce((names, name) => [`${names[0] || 'is'}-${name}`, ...names], [])); // generate names
```

this leads to different results, depending on the enumeration.

**To Reproduce**
- run helix-cli test on node10 vs node 12:

```
      + expected - actual

             "nb-text-3"
             "nb-blockquote-1"
             "nb-delete-1"
             "nb-heading-1"
      -      "is-html-text-blockquote"
      -      "is-html-text"
      -      "is-html"
      +      "is-text-html-blockquote"
      +      "is-text-html"
      +      "is-text"
           ]
         }
```

**Comment by ramboz** [comment]
The problem appears when there are multiple keys with the same count.
Say:
```js
{
  heading: 1,
  text: 1,
}
```
Depending on node version, they would be randomly sorted after comparing the count.

So enforcing alphabetical sorting on the keys if count is the same, can help:
```js
{
  heading: 1,
  text: 1,
}
```
=> stable `is-heading-text` (because `heading` < `text`), but changing this seems is could lead to breaking changes in the `is-…` API. Pre-existing checks may start failing because the generated type-list could now be different.
