### ISSUE TITLE
Add pathInfo to request

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#8]
| variable | comment |
| ---- | ---- |
| `request.pathInfo` | request path info, similar to [o.a.s.api.request.RequestPathInfo](https://sling.apache.org/apidocs/sling5/org/apache/sling/api/request/RequestPathInfo.html) |
| `request.pathInfo.path` | resource path |
| `request.pathInfo.extension` | extension |
| `request.pathInfo.selectors[]` | selectors |
| `request.pathInfo.selectorString` | selectors |
| `request.pathInfo.suffix` | suffix |

**Comment by tripodsan** [comment]
alternatively
- move those properties toplevel into the request object
- only use `selector` which contains the entire selectorString; since we currently do not want to support individual selector segments

**Comment by trieloff** [comment]
- I'd prefer to have them in the request object, not toplevel
- agree with `selector` only

**Comment by tripodsan** [comment]
since we don't to resource resolution, we can't support suffix neither, unless we can deduce it from the pattern (e.g. only when extension is present and only if suffix does not contains a dot).

for now it will be:

| variable | comment |
| ---- | ---- |
| `request.pathInfo` | request path info, similar to [o.a.s.api.request.RequestPathInfo](https://sling.apache.org/apidocs/sling5/org/apache/sling/api/request/RequestPathInfo.html) |
| `request.pathInfo.path` | resource path |
| `request.pathInfo.extension` | extension |
| `request.pathInfo.selector` | selectors |

Example:

`/en/welcome.print.preview.html`

| variable | value |
| ---- | ---- |
| `request.pathInfo.path` | `/en/welcome` |
| `request.pathInfo.extension` | `html` |
| `request.pathInfo.selector` | `print.preview` |

**Comment by tripodsan** [comment]
@trieloff @kptdobe what is about `contextPath` (eg: https://github.com/kptdobe/adobeio-helix/blob/5fedfb6b74359817a184a3fe24c3d328caabad2e/src/summary_html.pre.js#L27)

where would originate from ?

**Comment by kptdobe** [comment]
Temp fix.
My Petridish was not up-to-date and the `payload.path` I am receiving does not start with `/`. Also I struggled to compute links that works the same on Petridish and prod.
I am going to update to latest code and get rid of this (or open appropriate issues).

**Comment by tripodsan** [comment]
let's keep the current version w/o an explicit pathinfo object.
